"""Application constants -- department routing, email mappings, and category definitions."""

CATEGORIES = [
    "Waste Management",
    "Water Supply",
    "Sewage & Drainage",
    "Roads",
    "Electricity",
    "Other",
]

SUPPORTED_AUDIO_TYPES = ["audio"]

DEPARTMENT_EMAILS = {
    "Waste Management": "sakshameng2006@gmail.com",
    "Water Supply": "rittiqaaa001@gmail.com",
    "Roads": "thisisridhima1@gmail.com",
    "Sewage & Drainage": "gy69696699@gmail.com",
    "Electricity": "electricityeonvengeance@gmail.com",
    "Other": "eonaether17@gmail.com",
}

DEPARTMENT_GREETINGS = {
    "Waste Management": "Dear MCD Grievance Team,",
    "Water Supply": "Dear DJB Grievance Team,",
    "Roads": "Dear PWD Grievance Team,",
    "Sewage & Drainage": "Dear DJB Drainage Team,",
    "Electricity": "Dear BSES/TPDDL Grievance Team,",
    "Other": "Dear Nodal Grievance Officer,",
}

# Comprehensive ward mappings for major Delhi locations
WARD_MAPPINGS = {
    # Central Delhi
    "connaught place": "New Delhi Ward",
    "chandni chowk": "Chandni Chowk Ward",
    "karol bagh": "Karol Bagh Ward",
    "paharganj": "Karol Bagh Ward",
    "daryaganj": "Chandni Chowk Ward",
    
    # East Delhi  
    "shahdara": "Shahdara Ward",
    "mayur vihar": "Mayur Vihar Ward",
    "preet vihar": "Preet Vihar Ward",
    "anand vihar": "Anand Vihar Ward",
    "vivek vihar": "Vivek Vihar Ward",
    "karkarduma": "Karkarduma Ward",
    "dilshad garden": "Dilshad Garden Ward",
    "nand nagri": "Nand Nagri Ward",
    "seelampur": "Seelampur Ward",
    "gokulpuri": "Gokulpuri Ward",
    "jaffrabad": "Jaffrabad Ward",
    "maujpur": "Maujpur Ward",
    "karawal nagar": "Karawal Nagar Ward",
    "rohtas nagar": "Rohtas Nagar Ward",
    "yamuna vihar": "Seelampur Ward",
    "laxmi nagar": "Laxmi Nagar Ward",
    "laxmi nagar metro station": "Laxmi Nagar Ward",
    "patparganj": "Patparganj Ward",
    "lajpat nagar": "Lajpat Nagar Ward",
    "greater kailash": "Greater Kailash Ward",
    "nehru place": "Nehru Place Ward",
    
    # North Delhi
    "rohini": "Rohini Zone",
    "rohini sector 1": "Rohini Zone",
    "rohini sector 2": "Rohini Zone",
    "rohini sector 3": "Rohini Zone",
    "rohini sector 4": "Rohini Zone",
    "rohini sector 5": "Rohini Zone",
    "rohini sector 6": "Rohini Zone",
    "rohini sector 7": "Rohini Zone",
    "rohini sector 8": "Rohini Zone",
    "rohini sector 9": "Rohini Zone",
    "rohini sector 10": "Rohini Zone",
    "rohini sector 11": "Rohini Zone",
    "rohini sector 12": "Rohini Zone",
    "rohini sector 13": "Rohini Zone",
    "rohini sector 14": "Rohini Zone",
    "rohini sector 15": "Rohini Zone",
    "rohini sector 16": "Rohini Zone",
    "rohini sector 17": "Rohini Zone",
    "rohini sector 18": "Rohini Zone",
    "rohini sector 19": "Rohini Zone",
    "rohini sector 20": "Rohini Zone",
    "rohini sector 21": "Rohini Zone",
    "rohini sector 22": "Rohini Zone",
    "rohini sector 23": "Rohini Zone",
    "rohini sector 24": "Rohini Zone",
    "rohini sector 25": "Rohini Zone",
    "pitampura": "Pitampura Ward",
    "burari": "Burari Ward",
    "sultanpur majra": "Sultanpur Majra Ward",
    "bawana": "Bawana Ward",
    "narela": "Narela Ward",
    "mukundpur": "Pitampura Ward",
    "ashok vihar": "Pitampura Ward",
    
    # South Delhi
    "saket": "Saket Ward",
    "vasant kunj": "Vasant Kunj Ward",
    "malviya nagar": "Malviya Nagar Ward",
    "hauz khas": "Hauz Khas Ward",
    "green park": "Hauz Khas Ward",
    "defence colony": "Lajpat Nagar Ward",
    "kalkaji": "Greater Kailash Ward",
    "cr park": "Greater Kailash Ward",
    "okhla": "Okhla Ward",
    "badarpur": "Badarpur Ward",
    "mehrauli": "Mehrauli Ward",
    "chattarpur": "Mehrauli Ward",
    "sultanpur": "Mehrauli Ward",
    "pushp vihar": "Pitampura Ward",
    
    # West Delhi
    "dwarka": "Dwarka Zone",
    "dwarka sector 1": "Dwarka Zone",
    "dwarka sector 2": "Dwarka Zone",
    "dwarka sector 3": "Dwarka Zone",
    "dwarka sector 4": "Dwarka Zone",
    "dwarka sector 5": "Dwarka Zone",
    "dwarka sector 6": "Dwarka Zone",
    "dwarka sector 7": "Dwarka Zone",
    "dwarka sector 8": "Dwarka Zone",
    "dwarka sector 9": "Dwarka Zone",
    "dwarka sector 10": "Dwarka Zone",
    "dwarka sector 11": "Dwarka Zone",
    "dwarka sector 12": "Dwarka Zone",
    "dwarka sector 13": "Dwarka Zone",
    "dwarka sector 14": "Dwarka Zone",
    "dwarka sector 15": "Dwarka Zone",
    "dwarka sector 16": "Dwarka Zone",
    "dwarka sector 17": "Dwarka Zone",
    "dwarka sector 18": "Dwarka Zone",
    "dwarka sector 19": "Dwarka Zone",
    "dwarka sector 20": "Dwarka Zone",
    "dwarka sector 21": "Dwarka Zone",
    "dwarka sector 22": "Dwarka Zone",
    "dwarka sector 23": "Dwarka Zone",
    "dwarka mor": "Dwarka Zone",
    "janakpuri": "Janakpuri Ward",
    "uttam nagar": "Uttam Nagar Ward",
    "vikaspuri": "Vikaspuri Ward",
    "najafgarh": "Najafgarh Ward",
    "mustafabad": "Mustafabad Ward",
    "seemapuri": "Seemapuri Ward",
    "trilokpuri": "Trilokpuri Ward",
    "kirti nagar": "Kirti Nagar Ward",
    "rajouri garden": "Janakpuri Ward",
    "tilak nagar": "Janakpuri Ward",
    
    # Educational Institutions
    "nsut": "Dwarka Zone",
    "delhi university": "North Delhi",
    "jamia millia": "Okhla Ward",
    "jnu": "South Delhi",
    "iit delhi": "Hauz Khas Ward",
    
    # Major Metro Stations mapped to nearest wards
    "rajiv chowk metro": "New Delhi Ward",
    "kashmere gate metro": "North Delhi",
    "central secretariat metro": "New Delhi Ward",
    "aiims metro": "South Delhi",
    "ina metro": "South Delhi",
    "green park metro": "Hauz Khas Ward",
    "hauz khas metro": "Hauz Khas Ward",
    "malviya nagar metro": "Malviya Nagar Ward",
    "kalkaji mandir metro": "Greater Kailash Ward",
    "nehru enclave metro": "Nehru Place Ward",
    "okhla bird sanctuary metro": "Okhla Ward",
    "saket metro": "Saket Ward",
    "qutab minar metro": "Mehrauli Ward",
    "dwarka sector 21 metro": "Dwarka Zone",
    "rajouri garden metro": "Janakpuri Ward",
    "azadpur metro": "North Delhi",
    "shastri park metro": "Shahdara Ward",
    "anand vihar metro": "Anand Vihar Ward",
    "karkarduma metro": "Karkarduma Ward",
    "dilshad garden metro": "Dilshad Garden Ward",
    "shahdara metro": "Shahdara Ward",
    "welcome metro": "Shahdara Ward",
    "rohini east metro": "Rohini Zone",
    "rohini west metro": "Rohini Zone",
    "rithala metro": "Rohini Zone",
}
